export const WS_OPEN_PENDING = 'WS_OPEN_PENDING';
export const WS_OPEN_SUCCESS = 'WS_OPEN_SUCCESS';
export const WS_OPEN_ERROR = 'WS_OPEN_ERROR';

export const WS_DISCONNECTED = 'WS_DISCONNECTED';

export const WS_PEER_CONNECTED = 'WS_PEER_CONNECTED';
export const WS_PEER_DISCONNECTED = 'WS_PEER_DISCONNECTED';

export const WS_MESSAGE_SEND = 'WS_MESSAGE_SEND';
export const WS_MESSAGE_RECEIVED = 'WS_MESSAGE_RECEIVED';

export const PEER_STREAM_ADDED = 'PEER_STREAM_ADDED';

export const GET_VIDEO_STREAM = 'GET_VIDEO_STREAM';
