export const WS_OPEN_PENDING = 'WS_OPEN_PENDING';
export const WS_OPEN_SUCCESS = 'WS_OPEN_SUCCESS';
export const WS_OPEN_ERROR = 'WS_OPEN_ERROR';

export const WS_CLOSE = 'WS_CLOSE';

export const WS_MESSAGE_SEND = 'WS_MESSAGE_SEND';
export const WS_MESSAGE_RECEIVED = 'WS_MESSAGE_RECEIVED';
export const WS_MESSAGE_PROCEED_ERROR = 'WS_MESSAGE_PROCEED_ERROR';

export const JOIN_ROOM = 'JOIN_ROOM';
export const LEAVE_ROOM = 'LEAVE_ROOM';

export const LOCAL_STREAM_URL_RECEIVED = 'LOCAL_STREAM_URL_RECEIVED';
export const REMOTE_STREAM_URL_RECEIVED = 'REMOTE_STREAM_URL_RECEIVED';
